version: 2
jobs:
  build:
    docker:
      - image: elixir:1.6.1

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: cd cooler && mix deps.get
      - run: cd cooler && mix test
